// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// app/layout.tsx

// 'use client'

import './globals.css'
import { WagmiProvider } from 'wagmi'
import { wagmiConfig } from '@/lib/wagmi'
import Navbar from '@/components/navbar'

import ToastProvider from '@/components/toastProvider';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gradient-to-br from-purple-700 via-indigo-700 to-blue-700 text-white">
        {/* <WagmiProvider config={wagmiConfig}> */}
          {/* Global Navbar */}
          {/* <Navbar /> */}

          {/* Page Content */}
          {children}
        {/* </WagmiProvider> */}
        {/* <ToastProvider /> */}
      </body>
    </html>
  )
}

/*
WHAT THIS DOES
--------------

✔ Navbar is now shown on ALL pages automatically
✔ Wallet connection is shared across the app
✔ No need to import <Navbar /> in pages anymore
✔ Clean, scalable Next.js architecture

NEXT STEP
---------
Remove <Navbar /> from:
- app/page.tsx
- app/about/page.tsx
- app/contact/page.tsx
- app/mint/page.tsx
*/

